name: 部署VitePress

on:
  push:
    branches:
      - main # 这段是在推送到 docs 分支时触发该命令

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main # 这一步检查 docs 代码

      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '21.4.0' # 设置 nodejs 的版本

      - name: Install npm
        run: npm install -g npm # 全局安装 pnpm

      - name: Install dependencies
        run: npm install # 使用 pnpm 安装依赖

      - name: Build Project
        run: npm run build:prod

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.VUE3PROMOTE}} # 这一步很重要，单独看下面的大步骤，主要是用来给该脚本一些仓库权限
          publish_dir: ./dist
          publish_branch: gh-pages # 推送到关联仓库的 gh-pages 分支
          dotfiles: true # 包括在提交中，即使被 .gitignore 文件忽略